server:
  port: 8190
spring:
  datasource:
    url: jdbc:mysql://rab3tech.cbxai9cjf1gl.us-east-1.rds.amazonaws.com/customer_service_dev
    username: admin
    password: adminadmin    
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
 
sqs:
  queue:
    endpoint: https://sqs.us-east-1.amazonaws.com/054603371339/customer_service_dev
    name: customer_service_dev
    
aws:
  accesskey: AKIAIMHYFCEXGPHJK5PQ
  secretkey: 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

