server:
    port: 8190

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: 1234    
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

